/** Edit poly selection
 */
struct EditPolySelection_v
(
	_mod,
	
	function getAUsingB modOrObj bInVar aType:#currentLevel bType:#currentLevel =
	(
		
		
	),

	/*------------------------------------------------------------------------------
		PRIVATE
	--------------------------------------------------------------------------------*/
	
	function test =
	(
		messagebox "EditPolySelection.test()"
	)
)
